# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gopython.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0egopython.proto\"\x1a\n\nDisRequest\x12\x0c\n\x04path\x18\x01 \x01(\t\"\x17\n\x08\x44isReply\x12\x0b\n\x03\x64is\x18\x01 \x01(\x05\x32*\n\x04\x41lgo\x12\"\n\x06GetDis\x12\x0b.DisRequest\x1a\t.DisReply\"\x00\x42\x08Z\x06./;disb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gopython_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\006./;dis'
  _DISREQUEST._serialized_start=18
  _DISREQUEST._serialized_end=44
  _DISREPLY._serialized_start=46
  _DISREPLY._serialized_end=69
  _ALGO._serialized_start=71
  _ALGO._serialized_end=113
# @@protoc_insertion_point(module_scope)
