# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto import gopython_pb2 as gopython__pb2


class AlgoStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetDis = channel.unary_unary(
                '/Algo/GetDis',
                request_serializer=gopython__pb2.DisRequest.SerializeToString,
                response_deserializer=gopython__pb2.DisReply.FromString,
                )


class AlgoServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetDis(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AlgoServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetDis': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDis,
                    request_deserializer=gopython__pb2.DisRequest.FromString,
                    response_serializer=gopython__pb2.DisReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Algo', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Algo(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetDis(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Algo/GetDis',
            gopython__pb2.DisRequest.SerializeToString,
            gopython__pb2.DisReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
